baseURL = "https://scgmlz.github.io/hugo-theme-scgdoc/"
theme = "hugo-theme-scgdoc"
themesdir = "../.."
languageCode = "en-us"
title = "ProjectName"
MetaDataFormat = "toml"
canonifyURLs = true
sectionPagesMenu = "main"

paginate = 5

# Code
PygmentsCodeFences = true
PygmentsUseClassic = false
PygmentsUseClasses = true
PygmentsStyle = "vs"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "James Bond"
  email = "james.bond@gmail.com"
  custom_css = ["css/exampleSite.css"]
  logo = "img/site-logo.png"
  Debug = false


[[params.social]]
    title = "github"
    url = "https://github.com/gamesbond"

[params.authors.author1]
  name = "First Author"
  url = "http://first-author.com"
  
[params.authors.author2]
  name = "Second Author"
  url = "http://second-author.com"

[[menu.main]]
  name = "Home"
  identifier="home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "News"
  identifier="post"
  url = "/post/"
  weight = 20

[[menu.main]]
  name = "Documentation"
  identifier = "documentation"
  url = "/documentation/"
  weight = 30

